// <copyright file="GlobalSuppressions.cs" company="AndrewForster">
// Copyright (c) AndrewForster. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.CameraDevices")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.CameraSelectedCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.CurrentCamera")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.CurrentMicrophone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.FileSaveLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.IsCaptureDevicesSelected")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.IsCapturing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.LoadCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.MicrophoneDevices")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.MicrophoneSelectedCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.Title")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements must be documented", Justification = "Self Documenting", Scope = "member", Target = "~P:VideoCapature.Common.MainPageViewModel.ToggleCaptureStateCommand")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.cameraDeviceList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.cameraSelectedCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.currentCamera")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.currentMicrophone")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.fileSaveLocation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.isCapturing")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.loadCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.microphoneDeviceList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.microphoneSelectedCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.title")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "IgnoreStyle", Scope = "member", Target = "~F:VideoCapature.Common.MainPageViewModel.toggleCaptureStateCommand")]
